
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://swuqsvwhfqqgkomjibzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dXFzdndoZnFxZ2tvbWppYnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTA4NTYsImV4cCI6MjA2Mjg4Njg1Nn0.BKGRaCiPpZR7F6hD5XL8pYLPsWwXmBgerWN9w0jT7D8";

// Create Supabase client with improved configuration
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-application-name': 'cpa-practice-management',
    },
    // Add fetch options with timeout
    fetch: async (url, options) => {
      // Create a fresh AbortController for every request so parallel
      // requests don't share the same signal and inadvertently cancel
      // each other.
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000); // 10 second timeout

      try {
        const response = await fetch(url, {
          ...options,
          signal: controller.signal,
        });
        return response;
      } catch (error) {
        console.error("Supabase fetch error:", error);
        throw error;
      } finally {
        clearTimeout(timeoutId);
      }
    }
  }
});

// Helper function to check Supabase connection health
export const checkSupabaseConnection = async (): Promise<boolean> => {
  try {
    const start = Date.now();
    const { error } = await supabase.from('staff').select('count').limit(1);
    const elapsed = Date.now() - start;
    
    console.log(`Supabase connection check took ${elapsed}ms`);
    
    if (error) {
      console.error("Supabase connection check failed:", error);
      return false;
    }
    
    return true;
  } catch (err) {
    console.error("Failed to check Supabase connection:", err);
    return false;
  }
};
